# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 100, 361, 71))
        self.groupBox_5.setObjectName("groupBox_5")
        self.deviceNameLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.deviceNameLineEdit.setGeometry(QtCore.QRect(12, 30, 341, 31))
        self.deviceNameLineEdit.setReadOnly(True)
        self.deviceNameLineEdit.setObjectName("deviceNameLineEdit")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(240, 310, 161, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.drawWaterLabel = QtWidgets.QLabel(self.groupBox_6)
        self.drawWaterLabel.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.drawWaterLabel.setObjectName("drawWaterLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 180, 171, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.temperatureLcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.temperatureLcdNumber.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.temperatureLcdNumber.setObjectName("temperatureLcdNumber")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(240, 440, 161, 71))
        self.groupBox_8.setObjectName("groupBox_8")
        self.soundLabel = QtWidgets.QLabel(self.groupBox_8)
        self.soundLabel.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.soundLabel.setObjectName("soundLabel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 310, 181, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.waterLevelLedNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.waterLevelLedNumber.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.waterLevelLedNumber.setObjectName("waterLevelLedNumber")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 100, 441, 411))
        self.groupBox_4.setObjectName("groupBox_4")
        self.CameraGraphicsView = QtWidgets.QGraphicsView(self.groupBox_4)
        self.CameraGraphicsView.setGeometry(QtCore.QRect(10, 40, 421, 331))
        self.CameraGraphicsView.setObjectName("CameraGraphicsView")
        self.cameraLabel = QtWidgets.QLabel(self.groupBox_4)
        self.cameraLabel.setGeometry(QtCore.QRect(10, 390, 141, 16))
        self.cameraLabel.setObjectName("cameraLabel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 180, 181, 91))
        self.groupBox.setObjectName("groupBox")
        self.LedPictureLable = QtWidgets.QLabel(self.groupBox)
        self.LedPictureLable.setGeometry(QtCore.QRect(10, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LedPictureLable.setFont(font)
        self.LedPictureLable.setObjectName("LedPictureLable")
        self.ledStatusLabel = QtWidgets.QLabel(self.groupBox)
        self.ledStatusLabel.setGeometry(QtCore.QRect(50, 40, 51, 16))
        self.ledStatusLabel.setObjectName("ledStatusLabel")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(40, 440, 181, 71))
        self.groupBox_7.setObjectName("groupBox_7")
        self.feedLabel = QtWidgets.QLabel(self.groupBox_7)
        self.feedLabel.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.feedLabel.setObjectName("feedLabel")
        self.feedEnabledCheckBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.feedEnabledCheckBox.setGeometry(QtCore.QRect(300, 20, 71, 21))
        self.feedEnabledCheckBox.setObjectName("feedEnabledCheckBox")
        self.collectDataPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.collectDataPushButton.setGeometry(QtCore.QRect(410, 530, 111, 51))
        self.collectDataPushButton.setObjectName("collectDataPushButton")
        self.connectServerushButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectServerushButton.setGeometry(QtCore.QRect(530, 530, 111, 51))
        self.connectServerushButton.setObjectName("connectServerushButton")
        self.quitPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitPushButton.setGeometry(QtCore.QRect(740, 530, 111, 51))
        self.quitPushButton.setObjectName("quitPushButton")
        self.hardwareConfigPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.hardwareConfigPushButton.setGeometry(QtCore.QRect(40, 530, 111, 51))
        self.hardwareConfigPushButton.setObjectName("hardwareConfigPushButton")
        self.serverConfigPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.serverConfigPushButton.setGeometry(QtCore.QRect(170, 530, 111, 51))
        self.serverConfigPushButton.setObjectName("serverConfigPushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 431, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionzz = QtWidgets.QAction(MainWindow)
        self.actionzz.setObjectName("actionzz")
        self.actiondd = QtWidgets.QAction(MainWindow)
        self.actiondd.setObjectName("actiondd")
        self.actionds = QtWidgets.QAction(MainWindow)
        self.actionds.setObjectName("actionds")
        self.actionsdc = QtWidgets.QAction(MainWindow)
        self.actionsdc.setObjectName("actionsdc")
        self.actionsd = QtWidgets.QAction(MainWindow)
        self.actionsd.setObjectName("actionsd")
        self.actiondsdd = QtWidgets.QAction(MainWindow)
        self.actiondsdd.setObjectName("actiondsdd")
        self.actiontui = QtWidgets.QAction(MainWindow)
        self.actiontui.setObjectName("actiontui")
        self.actiondfg = QtWidgets.QAction(MainWindow)
        self.actiondfg.setObjectName("actiondfg")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action43 = QtWidgets.QAction(MainWindow)
        self.action43.setObjectName("action43")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action56 = QtWidgets.QAction(MainWindow)
        self.action56.setObjectName("action56")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action63 = QtWidgets.QAction(MainWindow)
        self.action63.setObjectName("action63")
        self.actionq = QtWidgets.QAction(MainWindow)
        self.actionq.setObjectName("actionq")
        self.menu.addAction(self.actionzz)
        self.menu.addAction(self.actiondd)
        self.menu.addSeparator()
        self.menu.addAction(self.actionsd)
        self.menu.addAction(self.actiondsdd)
        self.menu.addSeparator()
        self.menu.addAction(self.actiontui)
        self.menu_2.addAction(self.actionq)
        self.menu_3.addAction(self.action1)
        self.menu_3.addAction(self.action2)
        self.menu_3.addAction(self.action3)
        self.menu_3.addAction(self.action43)
        self.menu_3.addAction(self.action4)
        self.menu_3.addAction(self.action5)
        self.menu_3.addAction(self.action56)
        self.menu_3.addAction(self.action6)
        self.menu_3.addAction(self.action63)
        self.menu_4.addAction(self.actiondfg)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "微生态管家设备客户端 V1.0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "设备名称"))
        self.groupBox_6.setTitle(_translate("MainWindow", "抽水"))
        self.drawWaterLabel.setText(_translate("MainWindow", "已停止抽水"))
        self.groupBox_2.setTitle(_translate("MainWindow", "环境温度（℃）"))
        self.groupBox_8.setTitle(_translate("MainWindow", "声音"))
        self.soundLabel.setText(_translate("MainWindow", "已停止采集声音"))
        self.groupBox_3.setTitle(_translate("MainWindow", "水位（%）"))
        self.groupBox_4.setTitle(_translate("MainWindow", "摄像头"))
        self.cameraLabel.setText(_translate("MainWindow", "已停止采集摄像头"))
        self.groupBox.setTitle(_translate("MainWindow", "照明"))
        self.LedPictureLable.setText(_translate("MainWindow", "☀"))
        self.ledStatusLabel.setText(_translate("MainWindow", "已关闭"))
        self.groupBox_7.setTitle(_translate("MainWindow", "喂食"))
        self.feedLabel.setText(_translate("MainWindow", "已停止喂食"))
        self.feedEnabledCheckBox.setText(_translate("MainWindow", "启用"))
        self.collectDataPushButton.setText(_translate("MainWindow", "采集数据"))
        self.connectServerushButton.setText(_translate("MainWindow", "连接服务器"))
        self.quitPushButton.setText(_translate("MainWindow", "退出"))
        self.hardwareConfigPushButton.setText(_translate("MainWindow", "配置硬件"))
        self.serverConfigPushButton.setText(_translate("MainWindow", "配置服务器"))
        self.label.setText(_translate("MainWindow", "微生态管家设备客户端 V1.0"))
        self.menu.setTitle(_translate("MainWindow", "操作"))
        self.menu_2.setTitle(_translate("MainWindow", "服务器配置"))
        self.menu_3.setTitle(_translate("MainWindow", "硬件配置"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.actionzz.setText(_translate("MainWindow", "配置硬件"))
        self.actiondd.setText(_translate("MainWindow", "配置服务器"))
        self.actionds.setText(_translate("MainWindow", "上传数据"))
        self.actionsdc.setText(_translate("MainWindow", "退出"))
        self.actionsd.setText(_translate("MainWindow", "采集数据"))
        self.actiondsdd.setText(_translate("MainWindow", "连接服务器"))
        self.actiontui.setText(_translate("MainWindow", "退出"))
        self.actiondfg.setText(_translate("MainWindow", "关于..."))
        self.action1.setText(_translate("MainWindow", "设备名称"))
        self.action2.setText(_translate("MainWindow", "照明"))
        self.action3.setText(_translate("MainWindow", "环境温度"))
        self.action43.setText(_translate("MainWindow", "水位"))
        self.action4.setText(_translate("MainWindow", "抽水"))
        self.action5.setText(_translate("MainWindow", "喂食"))
        self.action56.setText(_translate("MainWindow", "声音"))
        self.action6.setText(_translate("MainWindow", "摄像头"))
        self.action63.setText(_translate("MainWindow", "63"))
        self.actionq.setText(_translate("MainWindow", "服务器"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
