# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HardwareConfig.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(951, 620)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(50, 70, 871, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 71, 31))
        self.label_2.setObjectName("label_2")
        self.deviceNameLineEdit = QtWidgets.QLineEdit(self.tab)
        self.deviceNameLineEdit.setGeometry(QtCore.QRect(170, 130, 371, 31))
        self.deviceNameLineEdit.setObjectName("deviceNameLineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 411, 31))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(170, 200, 491, 31))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ledEnableCheckBox = QtWidgets.QCheckBox(self.tab_2)
        self.ledEnableCheckBox.setGeometry(QtCore.QRect(20, 10, 91, 19))
        self.ledEnableCheckBox.setChecked(True)
        self.ledEnableCheckBox.setObjectName("ledEnableCheckBox")
        self.ledUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_2)
        self.ledUseEventFilesRadioButton.setGeometry(QtCore.QRect(20, 50, 115, 19))
        self.ledUseEventFilesRadioButton.setObjectName("ledUseEventFilesRadioButton")
        self.ledInputEventFileLabel = QtWidgets.QLabel(self.tab_2)
        self.ledInputEventFileLabel.setGeometry(QtCore.QRect(50, 80, 131, 20))
        self.ledInputEventFileLabel.setObjectName("ledInputEventFileLabel")
        self.ledInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.ledInputEventFileLineEdit.setGeometry(QtCore.QRect(150, 80, 551, 21))
        self.ledInputEventFileLineEdit.setObjectName("ledInputEventFileLineEdit")
        self.ledInputEventFilePushButton = QtWidgets.QPushButton(self.tab_2)
        self.ledInputEventFilePushButton.setGeometry(QtCore.QRect(710, 80, 41, 21))
        self.ledInputEventFilePushButton.setObjectName("ledInputEventFilePushButton")
        self.ledOutputEventFileLabel = QtWidgets.QLabel(self.tab_2)
        self.ledOutputEventFileLabel.setGeometry(QtCore.QRect(50, 110, 91, 20))
        self.ledOutputEventFileLabel.setObjectName("ledOutputEventFileLabel")
        self.ledOutputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.ledOutputEventFileLineEdit.setGeometry(QtCore.QRect(150, 110, 551, 21))
        self.ledOutputEventFileLineEdit.setObjectName("ledOutputEventFileLineEdit")
        self.ledOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_2)
        self.ledOutputEventFilePushButton.setGeometry(QtCore.QRect(710, 110, 41, 21))
        self.ledOutputEventFilePushButton.setObjectName("ledOutputEventFilePushButton")
        self.ledUsePinRadioButton = QtWidgets.QRadioButton(self.tab_2)
        self.ledUsePinRadioButton.setGeometry(QtCore.QRect(20, 160, 115, 19))
        self.ledUsePinRadioButton.setObjectName("ledUsePinRadioButton")
        self.ledPinPortLabel = QtWidgets.QLabel(self.tab_2)
        self.ledPinPortLabel.setGeometry(QtCore.QRect(50, 190, 72, 31))
        self.ledPinPortLabel.setObjectName("ledPinPortLabel")
        self.ledPinPortLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.ledPinPortLineEdit.setGeometry(QtCore.QRect(110, 190, 113, 31))
        self.ledPinPortLineEdit.setObjectName("ledPinPortLineEdit")
        self.ledPinPlatformLabel = QtWidgets.QLabel(self.tab_2)
        self.ledPinPlatformLabel.setGeometry(QtCore.QRect(300, 190, 72, 31))
        self.ledPinPlatformLabel.setObjectName("ledPinPlatformLabel")
        self.ledPinPlatformComboBox = QtWidgets.QComboBox(self.tab_2)
        self.ledPinPlatformComboBox.setGeometry(QtCore.QRect(340, 190, 87, 31))
        self.ledPinPlatformComboBox.setObjectName("ledPinPlatformComboBox")
        self.ledPinPlatformComboBox.addItem("")
        self.ledPinPlatformComboBox.addItem("")
        self.ledUseVirtualRadioButton = QtWidgets.QRadioButton(self.tab_2)
        self.ledUseVirtualRadioButton.setGeometry(QtCore.QRect(20, 260, 115, 19))
        self.ledUseVirtualRadioButton.setChecked(False)
        self.ledUseVirtualRadioButton.setObjectName("ledUseVirtualRadioButton")
        self.ledStatusLabel = QtWidgets.QLabel(self.tab_2)
        self.ledStatusLabel.setGeometry(QtCore.QRect(50, 290, 91, 31))
        self.ledStatusLabel.setObjectName("ledStatusLabel")
        self.ledOpenCloseComboBox = QtWidgets.QComboBox(self.tab_2)
        self.ledOpenCloseComboBox.setGeometry(QtCore.QRect(110, 290, 87, 31))
        self.ledOpenCloseComboBox.setObjectName("ledOpenCloseComboBox")
        self.ledOpenCloseComboBox.addItem("")
        self.ledOpenCloseComboBox.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.temperatureUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_3)
        self.temperatureUseEventFilesRadioButton.setGeometry(QtCore.QRect(10, 50, 115, 19))
        self.temperatureUseEventFilesRadioButton.setObjectName("temperatureUseEventFilesRadioButton")
        self.temperatureOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_3)
        self.temperatureOutputEventFilePushButton.setGeometry(QtCore.QRect(700, 110, 41, 21))
        self.temperatureOutputEventFilePushButton.setObjectName("temperatureOutputEventFilePushButton")
        self.temperatureInputEventFileLabel = QtWidgets.QLabel(self.tab_3)
        self.temperatureInputEventFileLabel.setGeometry(QtCore.QRect(40, 80, 131, 20))
        self.temperatureInputEventFileLabel.setObjectName("temperatureInputEventFileLabel")
        self.temperatureOutputEventFileLabel = QtWidgets.QLabel(self.tab_3)
        self.temperatureOutputEventFileLabel.setGeometry(QtCore.QRect(40, 110, 91, 20))
        self.temperatureOutputEventFileLabel.setObjectName("temperatureOutputEventFileLabel")
        self.temperatureEnableCheckBox = QtWidgets.QCheckBox(self.tab_3)
        self.temperatureEnableCheckBox.setGeometry(QtCore.QRect(10, 10, 161, 19))
        self.temperatureEnableCheckBox.setChecked(True)
        self.temperatureEnableCheckBox.setObjectName("temperatureEnableCheckBox")
        self.temperatureInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.temperatureInputEventFileLineEdit.setGeometry(QtCore.QRect(140, 80, 551, 21))
        self.temperatureInputEventFileLineEdit.setObjectName("temperatureInputEventFileLineEdit")
        self.temperatureInputEventFilePushButton = QtWidgets.QPushButton(self.tab_3)
        self.temperatureInputEventFilePushButton.setGeometry(QtCore.QRect(700, 80, 41, 21))
        self.temperatureInputEventFilePushButton.setObjectName("temperatureInputEventFilePushButton")
        self.temperatureValueLabel = QtWidgets.QLabel(self.tab_3)
        self.temperatureValueLabel.setGeometry(QtCore.QRect(40, 190, 91, 31))
        self.temperatureValueLabel.setObjectName("temperatureValueLabel")
        self.temperatureUseVirtualRadioButton = QtWidgets.QRadioButton(self.tab_3)
        self.temperatureUseVirtualRadioButton.setGeometry(QtCore.QRect(10, 160, 181, 19))
        self.temperatureUseVirtualRadioButton.setChecked(True)
        self.temperatureUseVirtualRadioButton.setObjectName("temperatureUseVirtualRadioButton")
        self.temperatureOutputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.temperatureOutputEventFileLineEdit.setGeometry(QtCore.QRect(140, 110, 551, 21))
        self.temperatureOutputEventFileLineEdit.setObjectName("temperatureOutputEventFileLineEdit")
        self.temperatureValueDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.temperatureValueDoubleSpinBox.setGeometry(QtCore.QRect(120, 190, 91, 31))
        self.temperatureValueDoubleSpinBox.setObjectName("temperatureValueDoubleSpinBox")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.waterLevelInputEventFileLabel = QtWidgets.QLabel(self.tab_4)
        self.waterLevelInputEventFileLabel.setGeometry(QtCore.QRect(50, 90, 131, 20))
        self.waterLevelInputEventFileLabel.setObjectName("waterLevelInputEventFileLabel")
        self.waterLevelValueDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.waterLevelValueDoubleSpinBox.setGeometry(QtCore.QRect(130, 200, 91, 31))
        self.waterLevelValueDoubleSpinBox.setObjectName("waterLevelValueDoubleSpinBox")
        self.waterLevelInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.waterLevelInputEventFileLineEdit.setGeometry(QtCore.QRect(150, 90, 551, 21))
        self.waterLevelInputEventFileLineEdit.setObjectName("waterLevelInputEventFileLineEdit")
        self.waterLevelEnableCheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.waterLevelEnableCheckBox.setGeometry(QtCore.QRect(20, 20, 161, 19))
        self.waterLevelEnableCheckBox.setChecked(True)
        self.waterLevelEnableCheckBox.setObjectName("waterLevelEnableCheckBox")
        self.waterLevelUseVirtualRadioButton = QtWidgets.QRadioButton(self.tab_4)
        self.waterLevelUseVirtualRadioButton.setGeometry(QtCore.QRect(20, 170, 181, 19))
        self.waterLevelUseVirtualRadioButton.setChecked(True)
        self.waterLevelUseVirtualRadioButton.setObjectName("waterLevelUseVirtualRadioButton")
        self.waterLevelValueLabel = QtWidgets.QLabel(self.tab_4)
        self.waterLevelValueLabel.setGeometry(QtCore.QRect(50, 200, 91, 31))
        self.waterLevelValueLabel.setObjectName("waterLevelValueLabel")
        self.waterLevelOutputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.waterLevelOutputEventFileLineEdit.setGeometry(QtCore.QRect(150, 120, 551, 21))
        self.waterLevelOutputEventFileLineEdit.setObjectName("waterLevelOutputEventFileLineEdit")
        self.waterLevelInputEventFilePushButton = QtWidgets.QPushButton(self.tab_4)
        self.waterLevelInputEventFilePushButton.setGeometry(QtCore.QRect(710, 90, 41, 21))
        self.waterLevelInputEventFilePushButton.setObjectName("waterLevelInputEventFilePushButton")
        self.waterLevelUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_4)
        self.waterLevelUseEventFilesRadioButton.setGeometry(QtCore.QRect(20, 60, 115, 19))
        self.waterLevelUseEventFilesRadioButton.setObjectName("waterLevelUseEventFilesRadioButton")
        self.waterLevelOutputEventFileLabel = QtWidgets.QLabel(self.tab_4)
        self.waterLevelOutputEventFileLabel.setGeometry(QtCore.QRect(50, 120, 91, 20))
        self.waterLevelOutputEventFileLabel.setObjectName("waterLevelOutputEventFileLabel")
        self.waterLevelOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_4)
        self.waterLevelOutputEventFilePushButton.setGeometry(QtCore.QRect(710, 120, 41, 21))
        self.waterLevelOutputEventFilePushButton.setObjectName("waterLevelOutputEventFilePushButton")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.drapWaterPinPortLabel = QtWidgets.QLabel(self.tab_5)
        self.drapWaterPinPortLabel.setGeometry(QtCore.QRect(40, 190, 72, 31))
        self.drapWaterPinPortLabel.setObjectName("drapWaterPinPortLabel")
        self.drapWaterUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_5)
        self.drapWaterUseEventFilesRadioButton.setGeometry(QtCore.QRect(10, 50, 115, 19))
        self.drapWaterUseEventFilesRadioButton.setObjectName("drapWaterUseEventFilesRadioButton")
        self.drapWaterOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_5)
        self.drapWaterOutputEventFilePushButton.setGeometry(QtCore.QRect(700, 110, 41, 21))
        self.drapWaterOutputEventFilePushButton.setObjectName("drapWaterOutputEventFilePushButton")
        self.drapWaterInputEventFileLabel = QtWidgets.QLabel(self.tab_5)
        self.drapWaterInputEventFileLabel.setGeometry(QtCore.QRect(40, 80, 131, 20))
        self.drapWaterInputEventFileLabel.setObjectName("drapWaterInputEventFileLabel")
        self.ledPinPortLineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.ledPinPortLineEdit_2.setGeometry(QtCore.QRect(100, 190, 113, 31))
        self.ledPinPortLineEdit_2.setObjectName("ledPinPortLineEdit_2")
        self.drapWaterOutputEventFileLabel = QtWidgets.QLabel(self.tab_5)
        self.drapWaterOutputEventFileLabel.setGeometry(QtCore.QRect(40, 110, 91, 20))
        self.drapWaterOutputEventFileLabel.setObjectName("drapWaterOutputEventFileLabel")
        self.drapWaterEnableCheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.drapWaterEnableCheckBox.setGeometry(QtCore.QRect(10, 10, 191, 19))
        self.drapWaterEnableCheckBox.setChecked(True)
        self.drapWaterEnableCheckBox.setObjectName("drapWaterEnableCheckBox")
        self.drapWaterStatusLabel = QtWidgets.QLabel(self.tab_5)
        self.drapWaterStatusLabel.setGeometry(QtCore.QRect(40, 290, 91, 31))
        self.drapWaterStatusLabel.setObjectName("drapWaterStatusLabel")
        self.drapWaterInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.drapWaterInputEventFileLineEdit.setGeometry(QtCore.QRect(140, 80, 551, 21))
        self.drapWaterInputEventFileLineEdit.setObjectName("drapWaterInputEventFileLineEdit")
        self.drapWaterInputEventFilePushButton = QtWidgets.QPushButton(self.tab_5)
        self.drapWaterInputEventFilePushButton.setGeometry(QtCore.QRect(700, 80, 41, 21))
        self.drapWaterInputEventFilePushButton.setObjectName("drapWaterInputEventFilePushButton")
        self.drapWaterOpenCloseComboBox = QtWidgets.QComboBox(self.tab_5)
        self.drapWaterOpenCloseComboBox.setGeometry(QtCore.QRect(150, 290, 111, 31))
        self.drapWaterOpenCloseComboBox.setObjectName("drapWaterOpenCloseComboBox")
        self.drapWaterOpenCloseComboBox.addItem("")
        self.drapWaterOpenCloseComboBox.addItem("")
        self.drapWaterUseVirtualRadioButton = QtWidgets.QRadioButton(self.tab_5)
        self.drapWaterUseVirtualRadioButton.setGeometry(QtCore.QRect(10, 260, 181, 19))
        self.drapWaterUseVirtualRadioButton.setChecked(False)
        self.drapWaterUseVirtualRadioButton.setObjectName("drapWaterUseVirtualRadioButton")
        self.drapWaterUsePinRadioButton = QtWidgets.QRadioButton(self.tab_5)
        self.drapWaterUsePinRadioButton.setGeometry(QtCore.QRect(10, 160, 115, 19))
        self.drapWaterUsePinRadioButton.setObjectName("drapWaterUsePinRadioButton")
        self.ledOutputEventFileLineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.ledOutputEventFileLineEdit_2.setGeometry(QtCore.QRect(140, 110, 551, 21))
        self.ledOutputEventFileLineEdit_2.setObjectName("ledOutputEventFileLineEdit_2")
        self.drapWaterPinPlatformComboBox = QtWidgets.QComboBox(self.tab_5)
        self.drapWaterPinPlatformComboBox.setGeometry(QtCore.QRect(330, 190, 87, 31))
        self.drapWaterPinPlatformComboBox.setObjectName("drapWaterPinPlatformComboBox")
        self.drapWaterPinPlatformComboBox.addItem("")
        self.drapWaterPinPlatformComboBox.addItem("")
        self.drapWaterPinPlatformLabel = QtWidgets.QLabel(self.tab_5)
        self.drapWaterPinPlatformLabel.setGeometry(QtCore.QRect(290, 190, 72, 31))
        self.drapWaterPinPlatformLabel.setObjectName("drapWaterPinPlatformLabel")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.feedPinPortLabel = QtWidgets.QLabel(self.tab_11)
        self.feedPinPortLabel.setGeometry(QtCore.QRect(40, 200, 72, 31))
        self.feedPinPortLabel.setObjectName("feedPinPortLabel")
        self.feedUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_11)
        self.feedUseEventFilesRadioButton.setGeometry(QtCore.QRect(10, 60, 115, 19))
        self.feedUseEventFilesRadioButton.setObjectName("feedUseEventFilesRadioButton")
        self.feedOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_11)
        self.feedOutputEventFilePushButton.setGeometry(QtCore.QRect(700, 120, 41, 21))
        self.feedOutputEventFilePushButton.setObjectName("feedOutputEventFilePushButton")
        self.feedInputEventFileLabel = QtWidgets.QLabel(self.tab_11)
        self.feedInputEventFileLabel.setGeometry(QtCore.QRect(40, 90, 131, 20))
        self.feedInputEventFileLabel.setObjectName("feedInputEventFileLabel")
        self.feedPinPortLineEdit = QtWidgets.QLineEdit(self.tab_11)
        self.feedPinPortLineEdit.setGeometry(QtCore.QRect(100, 200, 113, 31))
        self.feedPinPortLineEdit.setText("")
        self.feedPinPortLineEdit.setObjectName("feedPinPortLineEdit")
        self.feedOutputEventFileLabel = QtWidgets.QLabel(self.tab_11)
        self.feedOutputEventFileLabel.setGeometry(QtCore.QRect(40, 120, 91, 20))
        self.feedOutputEventFileLabel.setObjectName("feedOutputEventFileLabel")
        self.feedEnableCheckBox = QtWidgets.QCheckBox(self.tab_11)
        self.feedEnableCheckBox.setGeometry(QtCore.QRect(10, 20, 201, 19))
        self.feedEnableCheckBox.setChecked(True)
        self.feedEnableCheckBox.setObjectName("feedEnableCheckBox")
        self.feedInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_11)
        self.feedInputEventFileLineEdit.setGeometry(QtCore.QRect(140, 90, 551, 21))
        self.feedInputEventFileLineEdit.setText("")
        self.feedInputEventFileLineEdit.setObjectName("feedInputEventFileLineEdit")
        self.feedInputEventFilePushButton = QtWidgets.QPushButton(self.tab_11)
        self.feedInputEventFilePushButton.setGeometry(QtCore.QRect(700, 90, 41, 21))
        self.feedInputEventFilePushButton.setObjectName("feedInputEventFilePushButton")
        self.feedUseVirtualRadioButton = QtWidgets.QRadioButton(self.tab_11)
        self.feedUseVirtualRadioButton.setGeometry(QtCore.QRect(10, 270, 115, 19))
        self.feedUseVirtualRadioButton.setChecked(False)
        self.feedUseVirtualRadioButton.setObjectName("feedUseVirtualRadioButton")
        self.feedUsePinRadioButton = QtWidgets.QRadioButton(self.tab_11)
        self.feedUsePinRadioButton.setGeometry(QtCore.QRect(10, 170, 115, 19))
        self.feedUsePinRadioButton.setObjectName("feedUsePinRadioButton")
        self.feedOutputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_11)
        self.feedOutputEventFileLineEdit.setGeometry(QtCore.QRect(140, 120, 551, 21))
        self.feedOutputEventFileLineEdit.setText("")
        self.feedOutputEventFileLineEdit.setObjectName("feedOutputEventFileLineEdit")
        self.PinPlatformComboBox = QtWidgets.QComboBox(self.tab_11)
        self.PinPlatformComboBox.setGeometry(QtCore.QRect(330, 200, 87, 31))
        self.PinPlatformComboBox.setObjectName("PinPlatformComboBox")
        self.PinPlatformComboBox.addItem("")
        self.PinPlatformComboBox.addItem("")
        self.feedPinPlatformLabel = QtWidgets.QLabel(self.tab_11)
        self.feedPinPlatformLabel.setGeometry(QtCore.QRect(290, 200, 72, 31))
        self.feedPinPlatformLabel.setObjectName("feedPinPlatformLabel")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.soundLocalSoundLabel = QtWidgets.QLabel(self.tab_12)
        self.soundLocalSoundLabel.setGeometry(QtCore.QRect(40, 190, 72, 31))
        self.soundLocalSoundLabel.setObjectName("soundLocalSoundLabel")
        self.soundEnableCheckBox = QtWidgets.QCheckBox(self.tab_12)
        self.soundEnableCheckBox.setGeometry(QtCore.QRect(10, 10, 191, 19))
        self.soundEnableCheckBox.setChecked(True)
        self.soundEnableCheckBox.setObjectName("soundEnableCheckBox")
        self.soundLocalFileLabel = QtWidgets.QLabel(self.tab_12)
        self.soundLocalFileLabel.setGeometry(QtCore.QRect(40, 280, 91, 41))
        self.soundLocalFileLabel.setObjectName("soundLocalFileLabel")
        self.soundInputEventFileLabel = QtWidgets.QLabel(self.tab_12)
        self.soundInputEventFileLabel.setGeometry(QtCore.QRect(40, 80, 131, 20))
        self.soundInputEventFileLabel.setObjectName("soundInputEventFileLabel")
        self.soundOutputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.soundOutputEventFileLineEdit.setGeometry(QtCore.QRect(140, 110, 551, 21))
        self.soundOutputEventFileLineEdit.setObjectName("soundOutputEventFileLineEdit")
        self.soundUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_12)
        self.soundUseEventFilesRadioButton.setGeometry(QtCore.QRect(10, 50, 115, 19))
        self.soundUseEventFilesRadioButton.setObjectName("soundUseEventFilesRadioButton")
        self.soundOutputEventFileLabel = QtWidgets.QLabel(self.tab_12)
        self.soundOutputEventFileLabel.setGeometry(QtCore.QRect(40, 110, 91, 20))
        self.soundOutputEventFileLabel.setObjectName("soundOutputEventFileLabel")
        self.soundInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.soundInputEventFileLineEdit.setGeometry(QtCore.QRect(140, 80, 551, 21))
        self.soundInputEventFileLineEdit.setObjectName("soundInputEventFileLineEdit")
        self.soundUseLocalSoundRadioButton = QtWidgets.QRadioButton(self.tab_12)
        self.soundUseLocalSoundRadioButton.setGeometry(QtCore.QRect(10, 160, 115, 19))
        self.soundUseLocalSoundRadioButton.setObjectName("soundUseLocalSoundRadioButton")
        self.soundLocalSoundComboBox = QtWidgets.QComboBox(self.tab_12)
        self.soundLocalSoundComboBox.setGeometry(QtCore.QRect(110, 190, 581, 31))
        self.soundLocalSoundComboBox.setObjectName("soundLocalSoundComboBox")
        self.soundOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_12)
        self.soundOutputEventFilePushButton.setGeometry(QtCore.QRect(700, 110, 41, 21))
        self.soundOutputEventFilePushButton.setObjectName("soundOutputEventFilePushButton")
        self.soundInputEventFilePushButton = QtWidgets.QPushButton(self.tab_12)
        self.soundInputEventFilePushButton.setGeometry(QtCore.QRect(700, 80, 41, 21))
        self.soundInputEventFilePushButton.setObjectName("soundInputEventFilePushButton")
        self.soundUseLocalFileRadioButton = QtWidgets.QRadioButton(self.tab_12)
        self.soundUseLocalFileRadioButton.setGeometry(QtCore.QRect(10, 260, 181, 19))
        self.soundUseLocalFileRadioButton.setChecked(False)
        self.soundUseLocalFileRadioButton.setObjectName("soundUseLocalFileRadioButton")
        self.soundLocalFilePushButton = QtWidgets.QPushButton(self.tab_12)
        self.soundLocalFilePushButton.setGeometry(QtCore.QRect(700, 290, 41, 21))
        self.soundLocalFilePushButton.setObjectName("soundLocalFilePushButton")
        self.soundLocalFileLineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.soundLocalFileLineEdit.setGeometry(QtCore.QRect(120, 290, 571, 21))
        self.soundLocalFileLineEdit.setObjectName("soundLocalFileLineEdit")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.cameraOutputEventFilePushButton = QtWidgets.QPushButton(self.tab_13)
        self.cameraOutputEventFilePushButton.setGeometry(QtCore.QRect(710, 130, 41, 21))
        self.cameraOutputEventFilePushButton.setObjectName("cameraOutputEventFilePushButton")
        self.cameraLocalFileLabel = QtWidgets.QLabel(self.tab_13)
        self.cameraLocalFileLabel.setGeometry(QtCore.QRect(50, 300, 91, 41))
        self.cameraLocalFileLabel.setObjectName("cameraLocalFileLabel")
        self.cameraLocalFilePushButton = QtWidgets.QPushButton(self.tab_13)
        self.cameraLocalFilePushButton.setGeometry(QtCore.QRect(710, 310, 41, 21))
        self.cameraLocalFilePushButton.setObjectName("cameraLocalFilePushButton")
        self.cameraEnableCheckBox = QtWidgets.QCheckBox(self.tab_13)
        self.cameraEnableCheckBox.setGeometry(QtCore.QRect(20, 30, 191, 19))
        self.cameraEnableCheckBox.setChecked(True)
        self.cameraEnableCheckBox.setObjectName("cameraEnableCheckBox")
        self.cameraUseLocalCameraRadioButton = QtWidgets.QRadioButton(self.tab_13)
        self.cameraUseLocalCameraRadioButton.setGeometry(QtCore.QRect(20, 180, 115, 19))
        self.cameraUseLocalCameraRadioButton.setObjectName("cameraUseLocalCameraRadioButton")
        self.cameraUseLocalFileRadioButton = QtWidgets.QRadioButton(self.tab_13)
        self.cameraUseLocalFileRadioButton.setGeometry(QtCore.QRect(20, 280, 181, 19))
        self.cameraUseLocalFileRadioButton.setChecked(False)
        self.cameraUseLocalFileRadioButton.setObjectName("cameraUseLocalFileRadioButton")
        self.cameraInputEventFilePushButton = QtWidgets.QPushButton(self.tab_13)
        self.cameraInputEventFilePushButton.setGeometry(QtCore.QRect(710, 100, 41, 21))
        self.cameraInputEventFilePushButton.setObjectName("cameraInputEventFilePushButton")
        self.cameraLocalFileLineEdit = QtWidgets.QLineEdit(self.tab_13)
        self.cameraLocalFileLineEdit.setGeometry(QtCore.QRect(130, 310, 571, 21))
        self.cameraLocalFileLineEdit.setObjectName("cameraLocalFileLineEdit")
        self.cameraInputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_13)
        self.cameraInputEventFileLineEdit.setGeometry(QtCore.QRect(150, 100, 551, 21))
        self.cameraInputEventFileLineEdit.setObjectName("cameraInputEventFileLineEdit")
        self.cameraLocalcameraComboBox = QtWidgets.QComboBox(self.tab_13)
        self.cameraLocalcameraComboBox.setGeometry(QtCore.QRect(120, 210, 581, 31))
        self.cameraLocalcameraComboBox.setObjectName("cameraLocalcameraComboBox")
        self.cameraUseEventFilesRadioButton = QtWidgets.QRadioButton(self.tab_13)
        self.cameraUseEventFilesRadioButton.setGeometry(QtCore.QRect(20, 70, 115, 19))
        self.cameraUseEventFilesRadioButton.setObjectName("cameraUseEventFilesRadioButton")
        self.cameraInputEventFileLabel = QtWidgets.QLabel(self.tab_13)
        self.cameraInputEventFileLabel.setGeometry(QtCore.QRect(50, 100, 131, 20))
        self.cameraInputEventFileLabel.setObjectName("cameraInputEventFileLabel")
        self.cameraOutputEventFileLabel = QtWidgets.QLabel(self.tab_13)
        self.cameraOutputEventFileLabel.setGeometry(QtCore.QRect(50, 130, 91, 20))
        self.cameraOutputEventFileLabel.setObjectName("cameraOutputEventFileLabel")
        self.cameraLocalCameraLabel = QtWidgets.QLabel(self.tab_13)
        self.cameraLocalCameraLabel.setGeometry(QtCore.QRect(50, 210, 72, 31))
        self.cameraLocalCameraLabel.setObjectName("cameraLocalCameraLabel")
        self.cameraOutputEventFileLineEdit = QtWidgets.QLineEdit(self.tab_13)
        self.cameraOutputEventFileLineEdit.setGeometry(QtCore.QRect(150, 130, 551, 21))
        self.cameraOutputEventFileLineEdit.setObjectName("cameraOutputEventFileLineEdit")
        self.cameraStreamLabel = QtWidgets.QLabel(self.tab_13)
        self.cameraStreamLabel.setGeometry(QtCore.QRect(50, 380, 91, 41))
        self.cameraStreamLabel.setObjectName("cameraStreamLabel")
        self.cameraStreamLineEdit = QtWidgets.QLineEdit(self.tab_13)
        self.cameraStreamLineEdit.setGeometry(QtCore.QRect(130, 390, 571, 21))
        self.cameraStreamLineEdit.setObjectName("cameraStreamLineEdit")
        self.cameraUseStreamRadioButton = QtWidgets.QRadioButton(self.tab_13)
        self.cameraUseStreamRadioButton.setGeometry(QtCore.QRect(20, 360, 181, 19))
        self.cameraUseStreamRadioButton.setChecked(False)
        self.cameraUseStreamRadioButton.setObjectName("cameraUseStreamRadioButton")
        self.tabWidget.addTab(self.tab_13, "")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(430, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cancelPushButton = QtWidgets.QPushButton(Form)
        self.cancelPushButton.setGeometry(QtCore.QRect(830, 570, 93, 31))
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.setPushButton = QtWidgets.QPushButton(Form)
        self.setPushButton.setGeometry(QtCore.QRect(730, 570, 93, 31))
        self.setPushButton.setObjectName("setPushButton")
        self.okPushButton = QtWidgets.QPushButton(Form)
        self.okPushButton.setGeometry(QtCore.QRect(630, 570, 93, 31))
        self.okPushButton.setObjectName("okPushButton")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "硬件配置"))
        self.label_2.setText(_translate("Form", "设备名称"))
        self.label_3.setText(_translate("Form", "设备名称是服务器区分不同硬件的方式，需要唯一。"))
        self.label_6.setText(_translate("Form", "如果设备名称与连接服务器的其他设备同名，将无法连接到服务器。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "设备名称"))
        self.ledEnableCheckBox.setText(_translate("Form", "启用LED"))
        self.ledUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.ledInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.ledInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.ledOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.ledOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.ledUsePinRadioButton.setText(_translate("Form", "监控引脚"))
        self.ledPinPortLabel.setText(_translate("Form", "引脚号"))
        self.ledPinPlatformLabel.setText(_translate("Form", "平台"))
        self.ledPinPlatformComboBox.setItemText(0, _translate("Form", "树莓派"))
        self.ledPinPlatformComboBox.setItemText(1, _translate("Form", "JZ2440"))
        self.ledUseVirtualRadioButton.setText(_translate("Form", "模拟LED"))
        self.ledStatusLabel.setText(_translate("Form", "LED状态"))
        self.ledOpenCloseComboBox.setItemText(0, _translate("Form", "打开"))
        self.ledOpenCloseComboBox.setItemText(1, _translate("Form", "关闭"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "LED"))
        self.temperatureUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.temperatureOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.temperatureInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.temperatureOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.temperatureEnableCheckBox.setText(_translate("Form", "启用温度传感器"))
        self.temperatureInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.temperatureValueLabel.setText(_translate("Form", "温度(℃)："))
        self.temperatureUseVirtualRadioButton.setText(_translate("Form", "模拟温度传感器"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "温度传感器"))
        self.waterLevelInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.waterLevelEnableCheckBox.setText(_translate("Form", "启用水位传感器"))
        self.waterLevelUseVirtualRadioButton.setText(_translate("Form", "模拟水位传感器"))
        self.waterLevelValueLabel.setText(_translate("Form", "水位(%s)："))
        self.waterLevelInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.waterLevelUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.waterLevelOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.waterLevelOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "水位传感器"))
        self.drapWaterPinPortLabel.setText(_translate("Form", "引脚号"))
        self.drapWaterUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.drapWaterOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.drapWaterInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.drapWaterOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.drapWaterEnableCheckBox.setText(_translate("Form", "启用抽水电机控制器"))
        self.drapWaterStatusLabel.setText(_translate("Form", "抽水电机状态状态"))
        self.drapWaterInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.drapWaterOpenCloseComboBox.setItemText(0, _translate("Form", "正在抽水"))
        self.drapWaterOpenCloseComboBox.setItemText(1, _translate("Form", "停止抽水"))
        self.drapWaterUseVirtualRadioButton.setText(_translate("Form", "模拟抽水电机控制器"))
        self.drapWaterUsePinRadioButton.setText(_translate("Form", "监控引脚"))
        self.drapWaterPinPlatformComboBox.setItemText(0, _translate("Form", "树莓派"))
        self.drapWaterPinPlatformComboBox.setItemText(1, _translate("Form", "JZ2440"))
        self.drapWaterPinPlatformLabel.setText(_translate("Form", "平台"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "抽水电机控制器"))
        self.feedPinPortLabel.setText(_translate("Form", "引脚号"))
        self.feedUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.feedOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.feedInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.feedOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.feedEnableCheckBox.setText(_translate("Form", "启用喂食设备控制器"))
        self.feedInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.feedUseVirtualRadioButton.setText(_translate("Form", "模拟喂食设备控制器"))
        self.feedUsePinRadioButton.setText(_translate("Form", "监控引脚"))
        self.PinPlatformComboBox.setItemText(0, _translate("Form", "树莓派"))
        self.PinPlatformComboBox.setItemText(1, _translate("Form", "JZ2440"))
        self.feedPinPlatformLabel.setText(_translate("Form", "平台"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("Form", "喂食设备控制器"))
        self.soundLocalSoundLabel.setText(_translate("Form", "麦克风"))
        self.soundEnableCheckBox.setText(_translate("Form", "启用麦克风"))
        self.soundLocalFileLabel.setText(_translate("Form", "音频文件"))
        self.soundInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.soundUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.soundOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.soundUseLocalSoundRadioButton.setText(_translate("Form", "本地麦克风"))
        self.soundOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.soundInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.soundUseLocalFileRadioButton.setText(_translate("Form", "本地音频模拟"))
        self.soundLocalFilePushButton.setText(_translate("Form", "浏览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("Form", "麦克风"))
        self.cameraOutputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.cameraLocalFileLabel.setText(_translate("Form", "视频文件"))
        self.cameraLocalFilePushButton.setText(_translate("Form", "浏览"))
        self.cameraEnableCheckBox.setText(_translate("Form", "启用摄像头"))
        self.cameraUseLocalCameraRadioButton.setText(_translate("Form", "本地摄像头"))
        self.cameraUseLocalFileRadioButton.setText(_translate("Form", "本地视频模拟"))
        self.cameraInputEventFilePushButton.setText(_translate("Form", "浏览"))
        self.cameraUseEventFilesRadioButton.setText(_translate("Form", "使用事件文件"))
        self.cameraInputEventFileLabel.setText(_translate("Form", "输入事件文件"))
        self.cameraOutputEventFileLabel.setText(_translate("Form", "输出事件文件"))
        self.cameraLocalCameraLabel.setText(_translate("Form", "摄像头"))
        self.cameraStreamLabel.setText(_translate("Form", "视频流URL"))
        self.cameraUseStreamRadioButton.setText(_translate("Form", "视频流模拟"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("Form", "摄像头 "))
        self.label.setText(_translate("Form", "硬件配置"))
        self.cancelPushButton.setText(_translate("Form", "取消"))
        self.setPushButton.setText(_translate("Form", "应用"))
        self.okPushButton.setText(_translate("Form", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
